import AccessTimeIcon from "@mui/icons-material/AccessTime";
import ChatBubbleOutlineIcon from "@mui/icons-material/ChatBubbleOutline";

export const secondLatestDatas = [
    {
        imgone: 'https://cdn.pixabay.com/photo/2015/10/10/19/57/elderly-981400__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2016/07/01/22/34/people-1492052__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2016/11/19/10/40/woman-1838545__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2017/04/25/20/18/woman-2260736__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2018/02/21/15/06/woman-3170568__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2016/01/08/16/04/woman-1128523__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2016/11/21/17/02/adventure-1846482__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2020/01/21/13/23/freedom-4782870__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2016/11/19/09/45/man-1838330__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2016/03/09/09/30/woman-1245817__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    },
    {
        imgone: 'https://cdn.pixabay.com/photo/2017/04/05/01/15/ocean-2203720__480.jpg',
        type: 'FRANCE',
        desc: "Europe's Investment Banks resilient in retreat",
        imagetwo: 'https://cdn.pixabay.com/photo/2017/09/03/09/08/success-2709633__480.jpg',
        name: 'Salman',
        icon: <AccessTimeIcon fontSize="small"/>,
        time: '2 years ago',
        largeicon: <ChatBubbleOutlineIcon fontSize="small"/>,
        comment: 0,
    }
]